main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('event/', views.EventListView.as_view(), name='events'),
    path('event/<int:pk>',  views.EventDetailView.as_view(), name='event'),
    path('about', views.AboutUsView.as_view(), name='about_us'),
    path('reservation', views.ReservationCreateView.as_view(), name='reservation')
]

tour/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from tour import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Base(models.Model):
    create_datetime = models.DateTimeField('Дата создания', auto_now_add=True)
    update_datetime = models.DateTimeField('Дата создания', auto_now=True)
    on_delete = models.BooleanField('Удалено', default=False)


class MainData(models.Model):
    title = models.TextField('Текст', max_length=255, default='')
    description = models.CharField('Описание', max_length=255, default='')
    code = models.CharField('Код', max_length=255, default='')
    image = models.ImageField('Фото', blank=True, null=True, upload_to='main')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Параметр'
        verbose_name_plural = 'Основные данные сайта'


class Team(Base):
    title = models.CharField('Ф.И.О.', max_length=255)
    text = models.TextField('Описание', default='', blank=True, null=True)
    image = models.ImageField('Картинка', upload_to='media/teams/', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Участник команды'
        verbose_name_plural = 'Команда'


class IndexCarousel(Base):
    title = models.CharField('Заголовок', max_length=255)
    text = models.TextField('Полное описание', default='', blank=True, null=True)
    image = models.ImageField('Картинка', upload_to='media/carousel/', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Карусель'
        verbose_name_plural = 'Карусели'


class CategoryEvent(Base):
    name = models.CharField('Название', max_length=10, unique=True)
    code = models.CharField('Код', max_length=10, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория тура'
        verbose_name_plural = 'Категории туров'


class Event(models.Model):
    title = models.CharField('Название', max_length=255)
    description = models.CharField('Кратное описание', max_length=255)
    text = models.TextField('Полное описание', default='')
    image = models.ImageField('Картинка', upload_to='media/event/', blank=True, null=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.SET_NULL, blank=True, null=True)
    visible = models.BooleanField('Видимость для подписчиков', default=True)
    category = models.ForeignKey(CategoryEvent, verbose_name='Категория', on_delete=models.SET_NULL,
                                 blank=True, null=True)
    days = models.IntegerField('Колличество дней')
    old_price = models.DecimalField('Старая цена', decimal_places=2, max_digits=10, default=0)
    price = models.DecimalField('Цена в р. (0 для бесплаьного)', decimal_places=2, max_digits=10, default=0)
    eat = models.TextField('Еда (меню)', null=True, blank=True, default='')
    сonditions = models.TextField('Условия', null=True, blank=True, default='')
    sale = models.BooleanField('Акция', null=False, blank=True, default=False)
    # Системные настройки
    create_datetime = models.DateTimeField('Дата создания', auto_now_add=True)
    update_datetime = models.DateTimeField('Дата создания', auto_now=True)
    on_delete = models.BooleanField('Удалено', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тур'
        verbose_name_plural = 'Туры'


class EventCarousel(Base):
    title = models.CharField('Заголовок', max_length=255, blank=True, null=False, default='')
    description = models.CharField('Кратное описание', max_length=255,  blank=True, null=False, default='')
    text = models.TextField('Полное описание', default='', blank=True, null=False)
    image = models.ImageField('Картинка', upload_to='media/event_courses/', blank=True, null=True)
    event = models.ForeignKey(Event, verbose_name='Тур', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Карусель'
        verbose_name_plural = 'Карусели туров'


class EventProgram(Base):
    title = models.CharField('День', max_length=255)
    text = models.TextField('Полное описание', default='')
    image = models.ImageField('Картинка', upload_to='media/event_courses/', blank=True, null=True)
    event = models.ForeignKey(Event, verbose_name='Тур', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Программа по дням'
        verbose_name_plural = 'Программы по дням'


class EventEat(Base):
    title = models.CharField('День', max_length=255)
    image = models.ImageField('Картинка', upload_to='media/event_courses/', blank=True, null=True)
    event = models.ForeignKey(Event, verbose_name='Тур', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Фото еды'
        verbose_name_plural = 'Фото еды'


class Author(Base):
    title = models.CharField('Ф.И.О', max_length=255)
    description = models.CharField('Кратное описание', max_length=255)
    text = models.TextField('Полное описание', default='')
    image = models.ImageField('Картинка', upload_to='media/event_courses/', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class AboutUs(Base):
    title = models.CharField('Заголовок', max_length=255)
    text = models.TextField('Полное описание', default='')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'О нас'
        verbose_name_plural = 'О нас'


class Client(Base):
    name = models.CharField('Имя', max_length=255)
    email = models.CharField('Почта', max_length=255, blank=True, default='')
    phone = models.CharField('Телефон', max_length=255)
    comment = models.TextField('Комментарий', max_length=255, blank=True, default='')
    event = models.ForeignKey(Event, verbose_name='Тур', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.event.title}'

    class Meta:
        verbose_name = 'Бронь'
        verbose_name_plural = 'Бронь'

main/forms.py
from django.forms import ModelForm

from main.models import Client


class ReservationForm(ModelForm):

    class Meta:
        model = Client
        exclude = ('on_delete',)

main/views.py
from django.forms import forms
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, DetailView, ListView, CreateView
from main import models
from main.forms import ReservationForm


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['events'] = models.Event.objects.filter(visible=True)
        context['authors'] = models.Author.objects.all()
        context['carousel'] = models.IndexCarousel.objects.all()
        return context


class EventDetailView(DetailView):
    template_name = 'event.html'
    model = models.Event
    slug_field = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReservationForm()
        return context


class EventListView(ListView):
    template_name = 'events.html'
    queryset = models.Event.objects.filter(visible=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET.get('sale', None) == '1':
            context['object_list'] = models.Event.objects.filter(sale=True)
        if self.request.GET.get('type', None):
            context['object_list'] = models.Event.objects.filter(category__id=self.request.GET['type'])
        return context


class AboutUsView(ListView):
    template_name = 'about_us.html'
    model = models.AboutUs


class ReservationCreateView(CreateView):
    template_name = 'reservation.html'
    model = models.Client
    fields = ('name', 'email', 'phone', 'comment', 'event',)
    success_url = reverse_lazy('index')

main/templates/components/authors.html
{% load static %}
<div class="container marketing mt-4">
    <div class="row text-center justify-content-center">
        {% for author in authors %}
      <div class="col-lg-4">
        <img src="{{ author.image.url }}" class="bd-placeholder-img rounded-circle" width="140" height="140"  aria-label="Placeholder">
        <h2 class="fw-normal">{{ author.title }}</h2>
        <p>{{ author.description }}</p>
        <!--<p><a class="btn btn-success" href="#">Подробнее</a></p> -->
      </div><!-- /.col-lg-4 -->
        {% endfor %}
    </div>
</div>

main/templates/components/base.html
{% load static %}
{% load django_bootstrap5 %}

<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Курсы</title>

    {% bootstrap_css %}
    <!-- Иконки -->
    <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
          integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e"
          crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    {% bootstrap_messages %}
    {% block content %}
        <!-- Контент -->
    {% endblock %}
    {% bootstrap_javascript %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src=" {% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script src="{% static 'js/dark-light.js' %}"></script>
  </body>
</html>

main/templates/components/condition.html
{% block content %}
    <h1 class="text-center">Стоимость и условия</h1>
    <div class="row justify-content-center">
        <div class="col-md-6 p-5">
            <div class="p-2" style="border-radius: 10px; border: orange solid 2px;">
                {{ object.сonditions|safe }}
                <h2>
                    <p>
                        Старая цена:
                        <span class="text-decoration-line-through text-danger">{{ object.old_price }}</span>
                    </p>
                    <p class="text-success">
                        Новая цена:
                        {{object.price}}
                    </p>
                </h2>
                <button class="btn btn-success">Забронировать</button>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/components/event-carousel.html
{% load static %}
{% block content %}
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
      {%for item in object.eventcarousel_set.all %}
    <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
      <img src="{{item.image.url}}" style="position: relative" class="d-block w-100" alt="...">
        <div class="carousel-caption align-items-center" style="top:5%; bottom:5%; border-radius: 20px; padding: 0">
            <div class="p-1 align-items-center" style="margin-top: auto; margin-bottom:auto;background: rgba(53,164,255,0.45);">
                <h1 style="color: black; font-weight: bold">{{ object.title }}</h1>
                <p style="color: black;" >{{ object.description }}</p>
            </div>
      </div>
    </div>
      {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock %}

main/templates/components/event-eat-carousel.html
{% load static %}
{% block content %}
    <h1 class="text-center">Еда</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            {{ object.eat|safe }}
        </div>
    </div>
{% endblock %}

main/templates/components/event-program-carousel.html
{% load static %}
{% block content %}
    <h1 class="text-center">Программа</h1>
    <div id="carouselProgramControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner carousel-program">
      {%for item in object.eventprogram_set.all %}
        <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
            <div class="row">
                <div class="col p-3">
                    <img src="{{item.image.url}}" style="position: relative" class="d-block w-100" alt="...">
                </div>
                <div class="col p-3">
                    <h3 style="color: black; font-weight: bold">{{ item.title }}</h3>
                    <p style="color: black;" >{{ item.text|safe }}</p>
                </div>
            </div>
        </div>
      {% endfor %}
  </div>
  <button class="carousel-control-prev carousel-button"  type="button" data-bs-target="#carouselProgramControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" style="margin: auto" aria-hidden="true"></span>
  </button>
  <button class="carousel-control-next carousel-button" type="button" data-bs-target="#carouselProgramControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock %}

main/templates/components/index-carousel.html
{% load static %}
{% block content %}
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
          {% for item in carousel %}
              <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
              <img src="{{ item.image.url }}" style="position: relative" class="d-block w-100" alt="...">
                <div class="carousel-caption align-items-center" style="top:5%; bottom:5%; border-radius: 20px; padding: 0">
                    <div class="p-1 align-items-center" style="margin-top: auto; margin-bottom:auto;background: rgba(53,164,255,0.45);">
                        <h1 style="color: black; font-weight: bold">{{ item.title }}</h1>
                        <p style="color: black;" >{{ item.description }}</p>
                        <!--<button class="btn btn-success">Подробнее</button> -->
                    </div>
              </div>
            </div>
          {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
</div>
{% endblock %}

main/templates/components/index-events.html
{% load static %}
<hr class="featurette-divider">
{% for item in events %}
    <div class="flex-container">
        <div class="row">
          <div class="col-md-7 {% cycle 'order-1' 'order-0' %} p-4">
            <a class="link-body-emphasis" href="{% url 'event' item.id %}"><h2 class="featurette-heading fw-normal lh-1">{{item.title}}</h2></a>
            <p class="lead">{{item.description}}</p>
              <div class="row">
                  <div class="col-auto">
                     <a class="btn btn-success" href="{% url 'reservation' %}?event={{ item.id }}">Забронировать</a>
                  </div>
                  <div class="col-auto text-left">
                     <a class="btn btn-success" href="{% url 'event' item.id %}">Подробнее</a>
                  </div>
              </div>
          </div>
          <div class="col-md-5 {% cycle 'order-0' 'order-1' %} p-4">
            <img style="border: orange solid 1px" src="{{item.image.url}}" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
          </div>
        </div>
    </div>
    <hr class="featurette-divider">
{% endfor %}

main/templates/components/nav.html
{% load static %}
{% block content %}
<div class="row nav-header">
    <div class="col">
        <a class="ms-3 navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'img/logo.png' %}" alt="" height="90" class="d-inline-block align-text-center">
      </a>
    </div>
    <div class="col align-self-center">
        <div class="text-end me-3" style="">
                    <i class="m-1 bi bi-telephone-fill"></i>8928231296
        </div>
    </div>
</div>


    <nav class="navbar navbar-expand-md   justify-content-center" style="background: white; border: black solid 1px">
  <div class="container-fluid text-center">
        <button class="navbar-toggler"
                type="button"
                style="margin-left: auto;"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-lg-0" style="font-size: 1.8rem">
        <li class="nav-item align-items-center">
          <a class="nav-link" aria-current="page" href="{% url 'index' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about_us' %}">О нас</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Туры
          </a>
          <ul class="dropdown-menu">
            {% for item in categories %}
                <li><a class="dropdown-item" href="{% url 'events' %}?type={{item.id}}">{{ item.name }}</a></li>
              {% endfor %}
              <li><a class="dropdown-item" href="{% url 'events' %}">Все</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events' %}?sale=1" tabindex="-1" aria-disabled="true">Акции</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

main/templates/components/reservation.html
{% load django_bootstrap5 %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="block-reservation">
            <h1 class="text-center">Оставьте заявку. Мы перезвоним и всё расскажем!</h1>
            <form action="{% url 'reservation' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-end">
                    <button class="btn btn-success" type="submit">Отправить</button>
                </div>
            </form>
        </div>
    </div>
</div>
    <script>
    let event_element = document.getElementById('id_event')
    let event = '{{ object.id }}'
    console.log('jb')
    console.log(event)
    console.log('{{ request.GET.event }}')
    if (event) {
        event_element.parentElement.style.display = 'none'
        event_element.value = Number(event)
    }
    if ('{{ request.GET.event }}'){
        event_element.parentElement.style.display = 'none'
        event_element.value = Number('{{ request.GET.event }}')
    }

</script>
{% endblock %}